### ISSUE TITLE
Print Area

### ISSUE THREAD

**Issue by sennalb** [wreck-lab/wreck3D#9]
Hi,
where I can find print area dimensions ?
Thanks

**Comment by smark-** [comment]
> Hi,
> where I can find print area dimensions ?
> Thanks

The wreck3D-S has a build volume of 200x185 mm. I will add them to the Wiki

**Comment by sennalb** [comment]
Since wrek3d-s is a parametric printer  is It possible to establish a printing area and obtain the respective dimensions of the towers, sides and rods.
 I have not yet found a calculation system at this level.
Obviously within certain limits, for example if I wanted to get a 250x300 printing area which could be the lengths of the towers, sides and rods?

**Comment by smark-** [comment]
Given your volume requirements I would start from the wreck3D-M which has a build volume of 260x275. If you just increase the column height by 25 mm you can easily reach a total height of 300mm. We are planning to release the design files and the mounting instructions in mid April, as we did we the wreck3D-S. If you need it sooner please send us an e-mail at info@wrecklab.com
